% Use the MouseTracker to process the digital video and save the trajecotry
% file, then open the trajectory file with this code to get the heatmap
% Note: the pixelsize needs to be updated for different videos

clear all
clc

%% Defination of parameters
spheresize=30; % Estimate the size of the mouse in terms of pixels
imagesize_x=1980; % Image width in pixels
imagesize_y=1080; % Image height in pixels
HeatMap=zeros(imagesize_y,imagesize_x);
pixelsize=0.067; % Unit: cm
x=0:1:imagesize_x; 
x=x.*pixelsize;
x=x';
y=0:1:imagesize_y;
y=y.*pixelsize;
y=y';
Time_inter=1/5; % Time interval between frames in video processing

%% Read the filez
prompt = 'Get the trajctory file generated by MouseTracker';

[fname, pname]=uigetfile('*.*',prompt);
cd(pname)
a=load(fname);

if length(a(:,1))>9000 % Define the max number of frames according to the experiment duration
    a=a(1:30*60*5,:);
end

for ii=1:1:length(a)
    for jj=-spheresize:1:spheresize
        for kk=-spheresize:1:spheresize
            if jj.^2+kk.^2<=spheresize.^2
                if a(ii,1)+kk<=0
                    HeatMap(a(ii,2)+jj,1)=HeatMap(a(ii,2)+jj,1)+1;
                else
                    HeatMap(a(ii,2)+jj,a(ii,1)+kk)=HeatMap(a(ii,2)+jj,a(ii,1)+kk)+1;
                end
            end
        end
    end
end

HeatMap_Time=HeatMap.*Time_inter;
    
figure
ddd=[1 1 1;jet(100)];
colormap(ddd);
imagesc(x, y, HeatMap_Time)
caxis('auto')
colorbar
axis image

xlabel('x (cm)','fontsize',15,'FontName','Arial','FontWeight','bold')
ylabel('y (cm)','fontsize',15,'FontName','Arial','FontWeight','bold')
set(gca,'FontSize',15,'Linewidth',2)
title(fname)
 
c=colorbar;
c.Label.String = 'Time (s)';
c.Label.FontSize = 15;
c.FontName='Arial';
c.FontSize=15;
c.LineWidth=2;
   
save heat_map.dat HeatMap_Time -ascii