% Created 080630 by KDW
% Get the heatmap generated by the HeatMapPlotter and calculate the mean
% value inside a user-defined roi

% Get file names
[fnameR pnameR]=uigetfile('*.*','Select Real Image');
cd(pnameR);
%Display image
data=load(fnameR);
data=data.*(data>0);

figure
pcolor(data)
caxis('auto')

colormap jet;
axis image
axis xy
shading flat
axis off

%Take ROI
bw=roipolyarray(fnameR);

%Apply Mask
sprintf('%s','Signal')
maskeddata=bw.*data;

avg=mean(nonzeros(maskeddata));